[tool.poetry]
name = "bot"
version = "0.4.0"
description = "An operator bot for DABLChess."
authors = ["Digital Asset"]

[tool.poetry.dependencies]
python = "^3.7"
dazl = "^6.7.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
